"""
Stomatologik lug'at - Whisper transkripsiya va tarjima uchun.

Har bir atama 'groups' maydoniga ega - bu video uchun tanlangan
yo'nalishga qarab, Whisper'ga yuboriladigan 'maslahat' (prompt) uchun
faqat tegishli atamalarni tanlab olish imkonini beradi (OpenAI'ning
prompt maydoni cheklangan, ~200 so'z). Tarjimadan keyingi TUZATISH
bosqichi esa har doim BARCHA atamalar bilan ishlaydi - cheklovsiz.
"""

GLOSSARY_GROUPS = ['Umumiy stomatologiya / Anatomiya', 'Terapevtik stomatologiya (Endodontiya)', 'Ortopedik stomatologiya', 'Implantologiya', 'Jarrohlik stomatologiyasi', 'Ortodontiya', 'Parodontologiya', 'Bolalar stomatologiyasi', 'Radiologiya / Diagnostika / Patologiya', "Ma'muriy-sug'urta atamalari"]

GLOSSARY = [
    {"ru": "угол ANB", "uz": "ANB burchagi", "en": "ANB angle", "groups": ['Ortodontiya']},
    {"ru": "Центры услуг Medicare и Medicaid (CMS)", "uz": "CMS (AQSh davlat tibbiy sug'urta agentligi)", "en": "Centers for Medicare and Medicaid Services (CMS)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "I класс по Энглю (нейтральный прикус)", "uz": "I sinf Angle (neytral tishlam)", "en": "Class I (Angle)", "groups": ['Ortodontiya']},
    {"ru": "II класс по Энглю (дистальный прикус)", "uz": "II sinf Angle (distal tishlam)", "en": "Class II (Angle)", "groups": ['Ortodontiya']},
    {"ru": "III класс по Энглю (мезиальный прикус)", "uz": "III sinf Angle (mezial tishlam)", "en": "Class III (Angle)", "groups": ['Ortodontiya']},
    {"ru": "Кодекс стоматологических процедур и номенклатуры (CDT)", "uz": "Stomatologik muolajalar kodlari (CDT)", "en": "Code on Dental Procedures and Nomenclature (CDT Code)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "система CCO (Complete Clinical Orthodontics)", "uz": "CCO tizimi", "en": "Complete Clinical Orthodontics (CCO)", "groups": ['Ortodontiya']},
    {"ru": "Закон COBRA", "uz": "COBRA qonuni (AQSh)", "en": "Consolidated Omnibus Budget Reconciliation Act (COBRA)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "система Damon", "uz": "Damon tizimi", "en": "Damon system", "groups": ['Ortodontiya']},
    {"ru": "программа EPSDT (раннее выявление и лечение у детей)", "uz": "EPSDT dasturi (bolalarni erta tekshirish dasturi)", "en": "Early and Periodic Screening, Diagnosis and Treatment Program (EPSDT)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "доказательная стоматология", "uz": "dalillarga asoslangan stomatologiya", "en": "Evidence-Based Dentistry", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "франкфуртская горизонталь", "uz": "Frankfort gorizontali", "en": "Frankfort plane", "groups": ['Ortodontiya']},
    {"ru": "гнатион (Gn)", "uz": "Gnathion (Gn)", "en": "Gnathion (Gn)", "groups": ['Ortodontiya']},
    {"ru": "гонион (Go)", "uz": "Gonion (Go)", "en": "Gonion (Go)", "groups": ['Ortodontiya']},
    {"ru": "Закон HIPAA (о переносимости и подотчётности медстрахования)", "uz": "HIPAA qonuni (AQSh tibbiy ma'lumotlar maxfiyligi qonuni)", "en": "HIPAA", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "организация медицинского обеспечения (ХМО)", "uz": "HMO (sog'liqni saqlashni ta'minlash tashkiloti)", "en": "Health Maintenance Organization (HMO)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "Ассоциация индивидуальной практики (АИП)", "uz": "IPA (mustaqil amaliyot uyushmasi)", "en": "Individual Practice Association (IPA)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "Invisalign (система прозрачных элайнеров)", "uz": "Invisalign", "en": "Invisalign", "groups": ['Ortodontiya']},
    {"ru": "мэрилендский мост (адгезивный мост)", "uz": "Merilend ko'prigi (adgeziv ko'prik)", "en": "Maryland bridge", "groups": ['Ortopedik stomatologiya']},
    {"ru": "Medicaid / Medicare (программы медстрахования США)", "uz": "Medicaid / Medicare (AQSh davlat tibbiy sug'urta dasturlari)", "en": "Medicaid / Medicare", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "ментон (Me)", "uz": "Menton (Me)", "en": "Menton (Me)", "groups": ['Ortodontiya']},
    {"ru": "точка назион (N)", "uz": "Nasion (N) nuqtasi", "en": "Nasion (N)", "groups": ['Ortodontiya']},
    {"ru": "национальный идентификатор поставщика (NPI)", "uz": "NPI (milliy provayder identifikatori, AQSh)", "en": "National Provider Identifier (NPI)", "groups": ["Ma'muriy-sug'urta atamalari", 'Implantologiya']},
    {"ru": "никель-титановая дуга (NiTi)", "uz": "Niti sim (nikel-titan)", "en": "NiTi wire (Nickel-Titanium)", "groups": ['Ortodontiya']},
    {"ru": "орбитале (Or)", "uz": "Orbitale (Or)", "en": "Orbitale (Or)", "groups": ['Ortodontiya']},
    {"ru": "система Pitts 21", "uz": "Pitts21", "en": "Pitts 21", "groups": ['Ortodontiya']},
    {"ru": "погонион (Pog)", "uz": "Pogonion (Pog)", "en": "Pogonion (Pog)", "groups": ['Ortodontiya']},
    {"ru": "точка A (субспинале)", "uz": "A nuqta (Subspinale)", "en": "Point A (Subspinale)", "groups": ['Ortodontiya']},
    {"ru": "точка B (супраментале)", "uz": "B nuqta (Supramentale)", "en": "Point B (Supramentale)", "groups": ['Ortodontiya']},
    {"ru": "порион (Po)", "uz": "Porion (Po)", "en": "Porion (Po)", "groups": ['Ortodontiya']},
    {"ru": "эстетическая линия Рикеттса (E-линия)", "uz": "E-chiziq (Rikketts estetik chizig'i)", "en": "Ricketts' esthetic line (E-line)", "groups": ['Ortodontiya']},
    {"ru": "угол SNA", "uz": "SNA burchagi", "en": "SNA angle", "groups": ['Ortodontiya']},
    {"ru": "угол SNB", "uz": "SNB burchagi", "en": "SNB angle", "groups": ['Ortodontiya']},
    {"ru": "точка селла (S)", "uz": "Sella (S) nuqtasi", "en": "Sella (S)", "groups": ['Ortodontiya']},
    {"ru": "стандарт № 3950 (система нумерации зубов)", "uz": "3950-son standarti (tishlarni raqamlash tizimi)", "en": "Specification No. 3950 (tooth numbering system)", "groups": ["Ma'muriy-sug'urta atamalari", 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "титан-молибденовая дуга (TMA)", "uz": "TMA sim (titan-molibden qotishmasi)", "en": "TMA wire (Titanium-Molybdenum Alloy)", "groups": ['Ortodontiya']},
    {"ru": "универсальная/национальная система нумерации зубов", "uz": "universal/milliy tish raqamlash tizimi", "en": "Universal/National tooth numbering system", "groups": ["Ma'muriy-sug'urta atamalari", 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "анализ Witts", "uz": "Wits tahlili", "en": "Wits appraisal", "groups": ['Ortodontiya']},
    {"ru": "ось Y (ось роста)", "uz": "Y-o'qi", "en": "Y-axis", "groups": ['Ortodontiya']},
    {"ru": "абсцесс", "uz": "abssess", "en": "abscess", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "опора, абатмент", "uz": "abatment (tayanch tish/implant)", "en": "abutment", "groups": ['Ortopedik stomatologiya', 'Implantologiya']},
    {"ru": "опорная коронка", "uz": "tayanch toj (abatment toj)", "en": "abutment crown", "groups": ['Ortopedik stomatologiya']},
    {"ru": "регистрация образца", "uz": "namunani ro'yxatga olish", "en": "accession", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "кислотное протравливание", "uz": "kislota bilan ishlov berish (protravka)", "en": "acid etching", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "адгезия", "uz": "adgeziya (yopishish)", "en": "adhesion", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "адгезив", "uz": "adgeziv (yopishtiruvchi modda)", "en": "adhesive", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "вспомогательный, дополнительный", "uz": "qo'shimcha (yordamchi davolash)", "en": "adjunctive", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "административные расходы", "uz": "ma'muriy xarajatlar", "en": "administrative costs", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "услуги только по администрированию (АСО)", "uz": "faqat ma'muriy xizmatlar (ASO)", "en": "administrative services only (ASO)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "администратор программы", "uz": "dastur administratori", "en": "administrator", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "постоянный (взрослый) прикус", "uz": "doimiy (kattalar) tish qatori", "en": "adult dentition", "groups": ['Bolalar stomatologiyasi', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "неблагоприятный отбор", "uz": "noqulay tanlov (statistik holat)", "en": "adverse selection", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "выравнивание (алайнмент)", "uz": "alignment (qatorga solish bosqichi)", "en": "alignment", "groups": ['Ortodontiya']},
    {"ru": "аллогенный", "uz": "allogen", "en": "allogenic", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "аллопластический", "uz": "alloplastik", "en": "alloplastic", "groups": ['Implantologiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "допустимая сумма оплаты", "uz": "ruxsat etilgan to'lov summasi", "en": "allowable charge", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "сплав", "uz": "qotishma", "en": "alloy", "groups": ['Ortopedik stomatologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "альтернативная выплата", "uz": "muqobil to'lov sharti", "en": "alternate benefit", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "альтернативный план льгот", "uz": "muqobil sug'urta rejasi", "en": "alternative benefit plan", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "альтернативная система оказания услуг", "uz": "muqobil xizmat ko'rsatish tizimi", "en": "alternative delivery system", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "альвеолярный", "uz": "alveolyar", "en": "alveolar", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "alveolyar suyak", "en": "alveolar bone", "groups": ['Ortodontiya']},
    {"ru": "альвеолопластика", "uz": "alveoloplastika", "en": "alveoloplasty", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "амальгама", "uz": "amalgama", "en": "amalgam", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "анатомическая коронка", "uz": "anatomik toj", "en": "anatomical crown", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "анкораж (опора)", "uz": "tayanch (ankoraj)", "en": "anchorage", "groups": ['Ortodontiya']},
    {"ru": "вспомогательный", "uz": "yordamchi (qo'shimcha)", "en": "ancillary", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "анестезия (аналгезия, глубокая седация, общий наркоз, местная анестезия, минимальная/умеренная седация)", "uz": "anesteziya (analgeziya, chuqur sedatsiya, umumiy narkoz, mahalliy anesteziya, minimal/o'rtacha sedatsiya)", "en": "anesthesia (jumladan: analgesia, deep sedation, general anesthesia, local anesthesia, minimal/moderate sedation)", "groups": ['Jarrohlik stomatologiyasi', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "ангуляция (наклон коронки)", "uz": "angulyatsiya (tip)", "en": "angulation (tip)", "groups": ['Ortodontiya']},
    {"ru": "анкилоз зуба", "uz": "ankiloz", "en": "ankylosis", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "адентия / гиподентия", "uz": "adentiya (tug'ma tishsizlik)", "en": "anodontia / hypodontia", "groups": ['Ortodontiya', 'Bolalar stomatologiyasi']},
    {"ru": "аномалия", "uz": "anomaliya", "en": "anomaly", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "передний (фронтальный)", "uz": "oldingi (frontal) tishlar", "en": "anterior", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "анксиолизис", "uz": "anksiolizis (xavotirni kamaytirish)", "en": "anxiolysis", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "верхушка корня, апекс", "uz": "ildiz uchi (apeks)", "en": "apex", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "апексификация", "uz": "apeksifikatsiya", "en": "apexification", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "апексогенез", "uz": "apeksogenez", "en": "apexogenesis", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Bolalar stomatologiyasi']},
    {"ru": "апикальный базис", "uz": "apikal asos", "en": "apical base", "groups": ['Ortodontiya']},
    {"ru": "апикоэктомия, резекция верхушки корня", "uz": "apikoektomiya (ildiz uchini rezeksiya qilish)", "en": "apicoectomy", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "аппозиция (образование кости)", "uz": "apozitsiya", "en": "apposition", "groups": ['Ortodontiya']},
    {"ru": "зубной ряд, зубная дуга", "uz": "tish qatori (arka)", "en": "arch, dental", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "yoy simi (arch wire)", "en": "archwire", "groups": ['Ortodontiya']},
    {"ru": "прогиб дуги", "uz": "yoy ekstruziyasi (dugoning egilishi)", "en": "archwire deflection", "groups": ['Ortodontiya']},
    {"ru": "области полости рта (кодировка)", "uz": "og'iz bo'shlig'i sohalari (kodlash tizimi)", "en": "areas of oral cavity", "groups": ["Ma'muriy-sug'urta atamalari", 'Radiologiya / Diagnostika / Patologiya']},
    {"ru": "артрограмма", "uz": "artrogramma", "en": "arthrogram", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "артикуляция", "uz": "artikulyatsiya", "en": "articulation", "groups": ['Ortodontiya']},
    {"ru": "искусственная коронка", "uz": "sun'iy toj", "en": "artificial crown", "groups": ['Ortopedik stomatologiya']},
    {"ru": "переуступка выплат", "uz": "to'lovni o'tkazish (tayinlash)", "en": "assignment of benefits", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "заявление лечащего врача (устаревший термин)", "uz": "davolovchi shifokor bayonoti (eskirgan atama)", "en": "attending dentist's statement", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "аудит, проверка", "uz": "audit (tekshiruv)", "en": "audit", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "аутогенный", "uz": "autogen (o'z to'qimasidan)", "en": "autogenous", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "авульсия, полный вывих зуба", "uz": "avulsiya (tishning to'liq chiqib ketishi)", "en": "avulsion", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "недобросовестная страховая практика", "uz": "insofsiz sug'urta amaliyoti", "en": "bad faith insurance practices", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "выставление остатка счёта", "uz": "qolgan summani bemordan undirish", "en": "balance billing", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "барьерная мембрана", "uz": "to'siq membrana", "en": "barrier membrane", "groups": ['Jarrohlik stomatologiyasi', 'Parodontologiya']},
    {"ru": "управление поведением пациента", "uz": "bemor xulq-atvorini boshqarish", "en": "behavior management", "groups": ['Bolalar stomatologiyasi']},
    {"ru": "получатель льгот, застрахованный", "uz": "sug'urta egasi (foydalanuvchi)", "en": "beneficiary", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "страховая выплата", "uz": "sug'urta to'lovi", "en": "benefit", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "буклет с описанием льгот", "uz": "sug'urta shartlari bukleti", "en": "benefit booklet", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "краткое описание плана льгот", "uz": "sug'urta rejasi qisqacha tavsifi", "en": "benefit plan summary", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "доброкачественный", "uz": "xavfsiz (yaxshi sifatli)", "en": "benign", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "премоляр, малый коренной зуб", "uz": "kichik oziq tish (bikuspid)", "en": "bicuspid", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "двусторонний", "uz": "ikki tomonlama", "en": "bilateral", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "биологические материалы", "uz": "biologik materiallar", "en": "biologic materials", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "биопсия", "uz": "biopsiya", "en": "biopsy", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "бипротрузия", "uz": "biprotruda", "en": "biprotrusion", "groups": ['Ortodontiya']},
    {"ru": "правило дня рождения", "uz": "tug'ilgan kun qoidasi", "en": "birthday rule", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "", "uz": "tishlanish plastinkasi", "en": "bite plate", "groups": ['Ortodontiya']},
    {"ru": "прикусная (интерпроксимальная) рентгенограмма", "uz": "tishlanma (bayting) rentgenogrammasi", "en": "bitewing radiograph", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "отбеливание зубов", "uz": "tishlarni oqartirish", "en": "bleaching", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "корпусное перемещение (транслация)", "uz": "bodily movement (tana harakati)", "en": "bodily movement", "groups": ['Ortodontiya']},
    {"ru": "бондинг, склеивание", "uz": "bonding (yopishtirish)", "en": "bonding", "groups": ['Ortodontiya', 'Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "ограниченный дефект зубного ряда", "uz": "chegaralangan tish bo'shlig'i", "en": "bounded tooth space", "groups": ['Ortopedik stomatologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "breket", "en": "bracket", "groups": ['Ortodontiya']},
    {"ru": "база (основание) брекета", "uz": "breket asosi (bleyk)", "en": "bracket base", "groups": ['Ortodontiya']},
    {"ru": "мостовидный протез", "uz": "ko'prikli protez (bridge)", "en": "bridge", "groups": ['Ortopedik stomatologiya']},
    {"ru": "бруксизм", "uz": "bruksizm", "en": "bruxism", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "щёчный", "uz": "yonoq tomoni (bukkal)", "en": "buccal", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "объединение процедур", "uz": "muolajalarni birlashtirish", "en": "bundling of procedures", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "по отчёту (доп. tavsif talab qilinadi)", "uz": "hisobot asosida (qo'shimcha tavsif)", "en": "by report", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "байт-турбо", "uz": "bayt-turbo", "en": "byte turbo", "groups": ['Ortodontiya']},
    {"ru": "план «кафетерий» (гибкий пакет льгот)", "uz": "moslashuvchan imtiyozlar rejasi", "en": "cafeteria plan", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "зубной камень", "uz": "tish toshi (kamen)", "en": "calculus", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Parodontologiya']},
    {"ru": "канал (корневой канал, нижнечелюстной канал)", "uz": "kanal (ildiz kanali, pastki jag' kanali)", "en": "canal (root canal, mandibular canal)", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "", "uz": "ko'z tishi (klik)", "en": "canine", "groups": ['Ortodontiya']},
    {"ru": "консольное расширение протеза", "uz": "konsolli (osma) protez qismi", "en": "cantilever extension", "groups": ['Ortopedik stomatologiya']},
    {"ru": "капитация (подушевая оплата)", "uz": "kapitatsiya (jon boshiga to'lov)", "en": "capitation", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "кариес", "uz": "kariyes", "en": "caries", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "кариозное поражение", "uz": "kariyes shikastlanishi (kovagi)", "en": "carious lesion", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "ведение случая (кейс-менеджмент)", "uz": "bemor holatini boshqarish", "en": "case management", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "кариозная полость", "uz": "kovak (tish kovagi)", "en": "cavity", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "цементная прокладка (база)", "uz": "sement asos (baza)", "en": "cement base", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "цемент зуба", "uz": "sement (tish to'qimasi)", "en": "cementum", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "центр сопротивления", "uz": "qarshilik markazi", "en": "center of resistance", "groups": ['Ortodontiya']},
    {"ru": "центр вращения", "uz": "rotatsiya markazi", "en": "center of rotation", "groups": ['Ortodontiya']},
    {"ru": "центральная окклюзия", "uz": "sentrik okklyuziya", "en": "centric occlusion", "groups": ['Ortodontiya']},
    {"ru": "центральное соотношение", "uz": "sentrik relatsiya", "en": "centric relation", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "sefalometrik tahlil", "en": "cephalometric analysis", "groups": ['Ortodontiya']},
    {"ru": "цефалометрический снимок", "uz": "sefalometrik rasm (bosh o'lchov rentgeni)", "en": "cephalometric image", "groups": ['Ortodontiya', 'Radiologiya / Diagnostika / Patologiya']},
    {"ru": "цефалометрия", "uz": "sefalometriya", "en": "cephalometrics", "groups": ['Ortodontiya']},
    {"ru": "страховое требование (заявка на выплату)", "uz": "sug'urta so'rovnomasi (talabnomasi)", "en": "claim", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "бланк страхового требования", "uz": "sug'urta talabnomasi shakli", "en": "claim form", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "заявитель (по страховому требованию)", "uz": "talabnoma beruvchi shaxs", "en": "claimant", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "мошенничество при оплате требований", "uz": "to'lov bo'yicha firibgarlik", "en": "claims payment fraud", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "мошенничество при отчётности по требованиям", "uz": "hisobot bo'yicha firibgarlik", "en": "claims reporting fraud", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "", "uz": "I sinf malokklyuziya", "en": "class i malocclusion", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "II sinf malokklyuziya", "en": "class ii malocclusion", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "III sinf malokklyuziya", "en": "class iii malocclusion", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "shaffof kappa (aligner)", "en": "clear aligner", "groups": ['Ortodontiya']},
    {"ru": "расщелина нёба", "uz": "tanglay yorig'i (bo'linishi)", "en": "cleft palate", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "сжатие челюстей", "uz": "jag'larni siqish", "en": "clenching", "groups": ['Jarrohlik stomatologiyasi', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "клиническая коронка", "uz": "klinik toj", "en": "clinical crown", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "закрытая панель врачей", "uz": "yopiq shifokorlar ro'yxati (panel)", "en": "closed panel", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "закрытая репозиция (перелома)", "uz": "yopiq repozitsiya (sinishi)", "en": "closed reduction", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "пружина (койл-спринг)", "uz": "koyl (prujina)", "en": "coil spring", "groups": ['Ortodontiya']},
    {"ru": "долевое участие в оплате (коинсюренс)", "uz": "hamkorlikda to'lash ulushi", "en": "coinsurance", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "полный съёмный протез", "uz": "to'liq olinadigan protez", "en": "complete denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "полный рентгенологический комплект", "uz": "to'liq rentgen to'plami", "en": "complete series", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "композитный материал (композит)", "uz": "kompozit material", "en": "composite", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "открытый перелом", "uz": "ochiq sinish", "en": "compound fracture", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "мыщелок (головка нижней челюсти)", "uz": "kondil", "en": "condyle", "groups": ['Ortodontiya']},
    {"ru": "консультация", "uz": "konsultatsiya", "en": "consultation", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "врач по договору", "uz": "shartnoma bo'yicha shifokor", "en": "contract dentist", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "конвергенция", "uz": "konvergensiya", "en": "convergence", "groups": ['Ortodontiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "координация выплат (КОБ)", "uz": "to'lovlarni muvofiqlashtirish", "en": "coordination of benefits (COB)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "доплата пациента (сопла)", "uz": "bemor ustama to'lovi", "en": "copayment", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "колпачок (копинг)", "uz": "koping (yupqa qoplama)", "en": "coping", "groups": ['Ortopedik stomatologiya']},
    {"ru": "восстановление культи зуба", "uz": "tish kultyasini tiklash", "en": "core buildup", "groups": ['Ortopedik stomatologiya']},
    {"ru": "кортикотомия", "uz": "kortikotomiya", "en": "corticotomy", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "косметическая стоматология", "uz": "kosmetik stomatologiya", "en": "cosmetic dentistry", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "синдром треснувшего зуба", "uz": "yorilgan tish sindromi", "en": "cracked tooth syndrome", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "xoch (kesishgan) tishlanish", "en": "crossbite", "groups": ['Ortodontiya']},
    {"ru": "скученность зубов", "uz": "tishlar siqilishi (skuchennost)", "en": "crowding", "groups": ['Ortodontiya']},
    {"ru": "коронка", "uz": "toj (koronka)", "en": "crown", "groups": ['Ortopedik stomatologiya']},
    {"ru": "удлинение коронки зуба", "uz": "tojni uzaytirish (jarrohlik)", "en": "crown lengthening", "groups": ['Jarrohlik stomatologiyasi', 'Parodontologiya']},
    {"ru": "посев на микрофлору с определением чувствительности", "uz": "mikroorganizm ekmasi va antibiotiklarga sezuvchanlik testi", "en": "culture and sensitivity test", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "кюретаж", "uz": "kyuretaj", "en": "curettage", "groups": ['Parodontologiya']},
    {"ru": "кривая Шпее", "uz": "Spee egri chizig'i", "en": "curve of Spee", "groups": ['Ortodontiya']},
    {"ru": "кривая Уилсона", "uz": "Vilson egri chizig'i", "en": "curve of Wilson", "groups": ['Ortodontiya']},
    {"ru": "бугорок / клык", "uz": "kusp (bo'rtiqcha) / qoziq tish", "en": "cusp / cuspid", "groups": ['Parodontologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "киста (одонтогенная, периапикальная)", "uz": "kista (odontogen, periapikal)", "en": "cyst (odontogenic, periapical)", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "цитология", "uz": "sitologiya", "en": "cytology", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "", "uz": "halqalarni yechish", "en": "debanding", "groups": ['Ortodontiya']},
    {"ru": "дебондинг (снятие брекетов)", "uz": "debonding (yechish)", "en": "debonding", "groups": ['Ortodontiya']},
    {"ru": "дебридмент (очистка)", "uz": "debridment (tozalash)", "en": "debridement", "groups": ['Parodontologiya']},
    {"ru": "кариозное разрушение (в быту)", "uz": "yemirilish (kariyes, oddiy nom)", "en": "decay", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "молочный (о зубах)", "uz": "sut (tish haqida)", "en": "deciduous", "groups": ['Bolalar stomatologiyasi']},
    {"ru": "франшиза (невозмещаемая сумма)", "uz": "franshiza (bemor o'zi to'laydigan boshlang'ich summa)", "en": "deductible", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "дегисценция", "uz": "degisensiya", "en": "dehiscence", "groups": ['Ortodontiya', 'Parodontologiya']},
    {"ru": "зубная дуга", "uz": "tish yoyi", "en": "dental arch", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "стоматологический осмотр (оценка)", "uz": "stomatologik baholash", "en": "dental assessment", "groups": ['Radiologiya / Diagnostika / Patologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "дентин", "uz": "dentin", "en": "dentin", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "стоматология (как область медицины)", "uz": "stomatologiya (soha sifatida)", "en": "dentistry", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "прикус (молочный, постоянный, сменный, подростковый)", "uz": "tish qatori (sut, doimiy, almashinuvchi, o'smirlik)", "en": "dentition (deciduous, permanent, transitional, adolescent)", "groups": ['Bolalar stomatologiyasi', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "зубной протез / базис протеза", "uz": "protez / protez asosi (bazisi)", "en": "denture / denture base", "groups": ['Ortopedik stomatologiya']},
    {"ru": "деталинг (финишная отделка)", "uz": "deteyling", "en": "detailing", "groups": ['Ortodontiya']},
    {"ru": "диастема", "uz": "diastema", "en": "diastema", "groups": ['Ortodontiya']},
    {"ru": "прямое покрытие пульпы", "uz": "pulpani to'g'ridan-to'g'ri qoplash", "en": "direct pulp cap", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "прямая / непрямая реставрация", "uz": "to'g'ridan-to'g'ri / bilvosita restavratsiya", "en": "direct restoration / indirect restoration", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "дискэктомия", "uz": "diskektomiya", "en": "discectomy", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "смещённый зуб", "uz": "siljigan tish", "en": "displaced tooth", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "дистальный", "uz": "distal", "en": "distal", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "дистрактор", "uz": "distraktor", "en": "distractor", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "дивергенция", "uz": "divergensiya", "en": "divergence", "groups": ['Ortodontiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "занижение кода процедуры", "uz": "muolaja kodini pasaytirish", "en": "downcoding", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "повязка", "uz": "bog'lam (dressing)", "en": "dressing", "groups": ["Ma'muriy-sug'urta atamalari", 'Bolalar stomatologiyasi']},
    {"ru": "альвеолит (сухая лунка)", "uz": "quruq kataksa (alveolit)", "en": "dry socket", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "беззубый (адентия)", "uz": "tishsiz (adentiya)", "en": "edentulous", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "elastik (rezinka)", "en": "elastic band", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "elastik zanjircha", "en": "elastic chain", "groups": ['Ortodontiya']},
    {"ru": "эмаль", "uz": "emal", "en": "enamel", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "эндодонтия / эндодонтист", "uz": "endodontiya / endodontist", "en": "endodontics / endodontist", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "окклюзионная коррекция (пришлифовка)", "uz": "okklyuzion muvofiqlashtirish", "en": "equilibration", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "tish chiqishi", "en": "eruption", "groups": ['Ortodontiya']},
    {"ru": "постоянный пациент", "uz": "doimiy bemor", "en": "established patient", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "оценка (осмотр) пациента", "uz": "bemorni baholash (ko'rik)", "en": "evaluation", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "эвульсия (полный вывих зуба)", "uz": "evulsiya (tishning to'liq chiqib ketishi)", "en": "evulsion / avulsion", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "иссечение (эксцизия)", "uz": "kesib olib tashlash (ekssiziya)", "en": "excision", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "эксфолиативный", "uz": "eksfoliativ (po'st tashlovchi)", "en": "exfoliative", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "экзостоз / торус", "uz": "ekzostoz / torus", "en": "exostosis / torus", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "объяснение выплат (EOB)", "uz": "to'lov tushuntirish varaqasi (EOB)", "en": "explanation of benefits (EOB)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "учреждение длительного ухода", "uz": "uzoq muddatli parvarish muassasasi", "en": "extended care facility", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "внекоронковый / внутрикоронковый", "uz": "toj tashqarisidagi / toj ichidagi", "en": "extracoronal / intracoronal", "groups": ['Ortopedik stomatologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "экстракция (удаление зуба)", "uz": "tish ekstraksiyasi (sug'urib olish)", "en": "extraction", "groups": ['Jarrohlik stomatologiyasi', 'Ortodontiya']},
    {"ru": "", "uz": "olingan tish bo'shlig'i", "en": "extraction space", "groups": ['Ortodontiya']},
    {"ru": "внеротовой / внутриротовой", "uz": "og'iz tashqarisidagi / og'iz ichidagi", "en": "extraoral / intraoral", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "экструзивная сила", "uz": "ekstruziv kuch", "en": "extrusive force", "groups": ['Ortodontiya']},
    {"ru": "экссудат", "uz": "ekssudat", "en": "exudate", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "лицевой (вестибулярный)", "uz": "yuz (vestibulyar) tomon", "en": "facial", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "семейная франшиза", "uz": "oilaviy franshiza", "en": "family deductible", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "фасциальный", "uz": "fassial (fassiyaga oid)", "en": "fascial", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "усталость металла", "uz": "metall horg'inligi", "en": "fatigue of metal", "groups": ['Ortodontiya']},
    {"ru": "гонорар (полная такса, обычная такса, оплата за услугу, прайс-лист)", "uz": "to'lov (to'liq narx, odatiy narx, xizmat uchun to'lov, narxlar ro'yxati)", "en": "fee (full fee, usual fee, fee-for-service, fee schedule)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "фенестрация", "uz": "fenestratsiya", "en": "fenestration", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "пломба (бытовой термин)", "uz": "plomba (oddiy nom)", "en": "filling", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "несъёмный частичный протез (мостовидный)", "uz": "qo'zg'almas qisman protez (ko'prik)", "en": "fixed partial denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "гибкие льготы / гибкий сберегательный счёт", "uz": "moslashuvchan imtiyozlar / moslashuvchan jamg'arma hisobi", "en": "flexible benefits / flexible spending account", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "отверстие (в кости)", "uz": "teshik (suyakdagi)", "en": "foramen", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "перелом", "uz": "sinish (fraktura)", "en": "fracture", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "франчайзинговая стоматология", "uz": "franshiza asosidagi stomatologiya", "en": "franchise dentistry", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "свобода выбора врача", "uz": "shifokorni tanlash erkinligi", "en": "freedom of choice", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "уздечка", "uz": "yuganchak (frenulum)", "en": "frenum", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "сила трения", "uz": "ishqalanish kuchi", "en": "friction", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "funksional apparat", "en": "functional appliance", "groups": ['Ortodontiya']},
    {"ru": "фуркация (область разделения корней)", "uz": "furkatsiya (ildizlar ayrilish sohasi)", "en": "furcation", "groups": ['Parodontologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "система «привратника» (гейткипер)", "uz": "gatekeeper tizimi (nazoratchi shifokor)", "en": "gate keeper system", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "генетический тест", "uz": "genetik test", "en": "genetic test", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "десна", "uz": "milk (gingiva)", "en": "gingiva", "groups": ['Ortodontiya', 'Parodontologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "рецессия десны", "uz": "gingival (milk) retsessiyasi", "en": "gingival recession", "groups": ['Ortodontiya', 'Parodontologiya']},
    {"ru": "гингивэктомия", "uz": "gingivektomiya", "en": "gingivectomy", "groups": ['Parodontologiya']},
    {"ru": "гингивит", "uz": "gingivit", "en": "gingivitis", "groups": ['Parodontologiya']},
    {"ru": "гингивопластика", "uz": "gingivoplastika", "en": "gingivoplasty", "groups": ['Parodontologiya']},
    {"ru": "стеклоиономерный цемент", "uz": "shisha-ionomer sement", "en": "glass ionomer", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "золотая фольга", "uz": "oltin varaq (folga)", "en": "gold foil", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "гониальный угол", "uz": "goniya burchagi", "en": "gonial angle", "groups": ['Ortodontiya']},
    {"ru": "трансплантат (аллотрансплантат, аутотрансплантат)", "uz": "transplantat (allotransplantat, autotransplantat)", "en": "graft (allograft, autogenous graft)", "groups": ['Implantologiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "направленная регенерация тканей (НРТ)", "uz": "yo'naltirilgan to'qima regeneratsiyasi (GTR)", "en": "guided tissue regeneration (GTR)", "groups": ['Jarrohlik stomatologiyasi', 'Parodontologiya']},
    {"ru": "десневая улыбка", "uz": "gingival (dasnali) tabassum", "en": "gummy smile", "groups": ['Ortodontiya', 'Parodontologiya']},
    {"ru": "", "uz": "xoyli retayneri", "en": "hawley retainer", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "bosh apparat (headgear)", "en": "headgear", "groups": ['Ortodontiya']},
    {"ru": "гемисекция (разделение многокорневого зуба)", "uz": "gemiseksiya (ko'p ildizli tishni ikkiga bo'lish)", "en": "hemisection", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "гистопатология", "uz": "gistopatologiya", "en": "histopathology", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "оговорка об освобождении от ответственности", "uz": "javobgarlikdan ozod qilish bandi", "en": "hold harmless clause", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "гиалинизация", "uz": "gialinizatsiya", "en": "hyalinization", "groups": ['Ortodontiya']},
    {"ru": "гиперпластический", "uz": "giperplastik", "en": "hyperplastic", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "диагностическая визуализация", "uz": "diagnostik tasvirlash", "en": "imaging, diagnostic", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "непосредственный протез", "uz": "darhol o'rnatiladigan protez", "en": "immediate denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "ретинированный зуб", "uz": "retinirlangan (chiqmay qolgan) tish", "en": "impacted tooth", "groups": ['Jarrohlik stomatologiyasi', 'Ortodontiya']},
    {"ru": "ретенция (импакция) зуба", "uz": "tish retensiyasi (impaksiya)", "en": "impaction", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "имплантат (эндостальный, субпериостальный, трансостальный)", "uz": "implant (endosteal, subperiosteal, transosteal)", "en": "implant (endosteal, subperiosteal, transosteal)", "groups": ['Implantologiya']},
    {"ru": "", "uz": "ottisk (qolip)", "en": "impression", "groups": ['Ortodontiya']},
    {"ru": "недобросовестные практики снижения гонорара", "uz": "haqqoniy bo'lmagan chegirma amaliyotlari", "en": "inappropriate fee discounting practices", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "программа стимулирования", "uz": "rag'batlantirish dasturi", "en": "incentive program", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "режущий край / резец", "uz": "kesuvchi qirra / kurak tish", "en": "incisal / incisor", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "разрез и дренирование", "uz": "kesish va drenaj qilish", "en": "incision and drainage", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "", "uz": "kurak tish", "en": "incisor", "groups": ['Ortodontiya']},
    {"ru": "план возмещения (индемнити)", "uz": "qoplama (indemniti) rejasi", "en": "indemnity plan", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "непрямое покрытие пульпы", "uz": "pulpani bilvosita qoplash", "en": "indirect pulp cap", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "инфраокклюзия", "uz": "infraokklyuzion holat", "en": "infraocclusion", "groups": ['Ortodontiya']},
    {"ru": "вкладка / накладка (инлей / онлей)", "uz": "vkladka (inley) / накладка (onley)", "en": "inlay / onlay", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Ortopedik stomatologiya']},
    {"ru": "страховщик / застрахованный", "uz": "sug'urtalovchi / sug'urtalangan shaxs", "en": "insurer / insured", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "преднамеренная реплантация зуба", "uz": "ataylab qayta implantatsiya (reimplantatsiya)", "en": "intentional reimplantation", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "", "uz": "erta (ogohlantiruvchi) davolash", "en": "interceptive treatment", "groups": ['Ortodontiya']},
    {"ru": "межзубный (интерпроксимальный)", "uz": "tishlararo (interproksimal)", "en": "interproximal", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "интрузивная сила", "uz": "intruziv kuch", "en": "intrusive force", "groups": ['Ortodontiya']},
    {"ru": "челюсть (верхняя, нижняя)", "uz": "jag' (yuqori, pastki)", "en": "jaw (maxilla, mandible)", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "кератин / кератинизированная десна", "uz": "keratin / keratinlashgan milk", "en": "keratin / keratinized gingiva", "groups": ['Parodontologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "губной (лабиальный) / язычный (лингвальный)", "uz": "lab tomoni (labial) / til tomoni (lingval)", "en": "labial / lingual", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "ламинатный винир", "uz": "laminat vinir", "en": "laminate veneer", "groups": ['Ortopedik stomatologiya']},
    {"ru": "наименее затратное альтернативное лечение (LEAT)", "uz": "eng arzon muqobil davolash (LEAT)", "en": "least expensive alternative treatment (LEAT)", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "повреждение, поражение (лезия)", "uz": "shikastlanish (lesiya)", "en": "lesion", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "нивелирование (левелинг)", "uz": "levelling (tekislash bosqichi)", "en": "levelling", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "ligatura", "en": "ligature", "groups": ['Ortodontiya']},
    {"ru": "линейный угол", "uz": "chiziqli burchak", "en": "line angle", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "макродентия", "uz": "makrodontiya", "en": "macrodontia", "groups": ['Ortodontiya', 'Bolalar stomatologiyasi']},
    {"ru": "макрогнатия", "uz": "makrognatiya", "en": "macrognathia", "groups": ['Ortodontiya']},
    {"ru": "поддерживающая пародонтальная терапия", "uz": "parodontal saqlab turish davosi", "en": "maintenance, periodontal", "groups": ['Parodontologiya']},
    {"ru": "злокачественный", "uz": "xavfli (malign)", "en": "malignant", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "неправильный прикус (аномалия окклюзии)", "uz": "noto'g'ri tishlanish (malokklyuziya)", "en": "malocclusion", "groups": ['Ortodontiya']},
    {"ru": "управляемая медицинская помощь", "uz": "boshqariladigan tibbiy yordam", "en": "managed care", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "нижняя челюсть / верхняя челюсть", "uz": "pastki jag' / yuqori jag'", "en": "mandible / maxilla", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "нёбный расширитель (экспандер)", "uz": "ekspander (yuqori jag' kengaytirgichi)", "en": "maxillary expander", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "медицински необходимая помощь", "uz": "tibbiy jihatdan zarur yordam", "en": "medically necessary care", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "лекарственное средство (медикамент)", "uz": "dori vositasi (medikament)", "en": "medicament", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "классификация металлов (сплавов)", "uz": "metallar (qotishmalar) tasnifi", "en": "metals, classification of", "groups": ['Ortopedik stomatologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "микроабразия", "uz": "mikroabraziya", "en": "microabrasion", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "микродентия", "uz": "mikrodontiya", "en": "microdontia", "groups": ['Ortodontiya', 'Bolalar stomatologiyasi']},
    {"ru": "микрогнатия", "uz": "mikrognatiya", "en": "micrognathia", "groups": ['Ortodontiya']},
    {"ru": "микроорганизмы", "uz": "mikroorganizmlar", "en": "microorganisms", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "", "uz": "o'rta chiziq", "en": "midline", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "aralash tishlar davri", "en": "mixed dentition", "groups": ['Ortodontiya']},
    {"ru": "моляр (большой коренной зуб)", "uz": "katta oziq tish (molyar)", "en": "molar", "groups": ['Ortodontiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "molyar halqa", "en": "molar band", "groups": ['Ortodontiya']},
    {"ru": "момент силы", "uz": "kuch momenti", "en": "moment of force", "groups": ['Ortodontiya']},
    {"ru": "капа (защитная)", "uz": "himoya kapasi (mautgard)", "en": "mouthguard", "groups": ['Ortopedik stomatologiya', 'Bolalar stomatologiyasi']},
    {"ru": "слизистая оболочка", "uz": "shilliq parda (mukoza)", "en": "mucous membrane", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "миотерапия", "uz": "mioterapiya", "en": "myotherapy", "groups": ['Ortodontiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "необходимое лечение", "uz": "zarur davolash", "en": "necessary treatment", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "неаутогенный (донорский)", "uz": "boshqa donorga oid (autogen bo'lmagan)", "en": "non-autogenous", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "недопущение дублирования выплат", "uz": "to'lovlar takrorlanishining oldini olish", "en": "nonduplication of benefits", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "врач вне сети (без договора)", "uz": "shartnomasiz shifokor", "en": "nonparticipating dentist", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "обтурировать / обтуратор", "uz": "obturatsiya qilish / obturator", "en": "obturate / obturator", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "окклюзионный / окклюзия", "uz": "okklyuzion / okklyuziya", "en": "occlusal / occlusion", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "окклюзионная плоскость", "uz": "okklyuzion tekislik", "en": "occlusal plane", "groups": ['Ortodontiya']},
    {"ru": "окклюзионная рентгенограмма", "uz": "okklyuzion rentgenogramma", "en": "occlusal radiograph", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "", "uz": "okklyuziya (tishlanish)", "en": "occlusion", "groups": ['Ortodontiya']},
    {"ru": "одонтогенный", "uz": "odontogen", "en": "odontogenic", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "одонтопластика", "uz": "odontoplastika", "en": "odontoplasty", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "", "uz": "ochiq tishlanish", "en": "open bite", "groups": ['Ortodontiya']},
    {"ru": "период открытой регистрации", "uz": "ochiq ro'yxatga olish davri", "en": "open enrollment", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "открытая панель врачей", "uz": "ochiq shifokorlar ro'yxati", "en": "open panel", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "открытая репозиция (перелома)", "uz": "ochiq repozitsiya (sinishi)", "en": "open reduction", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "операкулэктомия / оперкулум", "uz": "operkulektomiya / operkulum", "en": "operculectomy / operculum", "groups": ['Jarrohlik stomatologiyasi', 'Bolalar stomatologiyasi']},
    {"ru": "патолог челюстно-лицевой области / патология", "uz": "og'iz va jag'-yuz patologiyasi (mutaxassisi)", "en": "oral and maxillofacial pathologist / pathology", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "рентгенолог челюстно-лицевой области / рентгенология", "uz": "og'iz va jag'-yuz radiologiyasi (mutaxassisi)", "en": "oral and maxillofacial radiologist / radiology", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "челюстно-лицевой хирург / хирургия", "uz": "og'iz va jag'-yuz jarrohi / jarrohligi", "en": "oral and maxillofacial surgeon / surgery", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "стоматологическая диагностика", "uz": "og'iz bo'shlig'i tashxisi", "en": "oral diagnosis", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "ортодонт / ортодонтия и зубочелюстная ортопедия", "uz": "ortodont / ortodontiya va tish-jag' ortopediyasi", "en": "orthodontist / orthodontics and dentofacial orthopedics", "groups": ['Ortodontiya']},
    {"ru": "ортогнатический", "uz": "ortognatik", "en": "orthognathic", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "остеопластика / остеотомия", "uz": "osteoplastika / osteotomiya", "en": "osteoplasty / osteotomy", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "завышение счёта / завышение кода", "uz": "haddan ortiq hisob-kitob / kodni oshirib ko'rsatish", "en": "overbilling / overcoding", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "глубина резцового перекрытия (овербайт)", "uz": "chuqur tishlanish", "en": "overbite", "groups": ['Ortodontiya']},
    {"ru": "покрывной протез (овердентура)", "uz": "qoplama protez (overdentura)", "en": "overdenture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "сагиттальная щель (оверджет)", "uz": "gorizontal chiqiqlik", "en": "overjet", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "tanglay kengaytirgichi", "en": "palatal expander", "groups": ['Ortodontiya']},
    {"ru": "нёбо", "uz": "tanglay", "en": "palate", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "паллиативный", "uz": "palliativ (og'riqni kamaytiruvchi)", "en": "palliative", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "панорамная рентгенограмма (ОПТГ)", "uz": "panoramik rentgenogramma (OPTG)", "en": "panoramic radiograph", "groups": ['Ortodontiya', 'Radiologiya / Diagnostika / Patologiya']},
    {"ru": "иммобилизирующая доска (papoose board)", "uz": "cheklovchi taxta (papoose board)", "en": "papoose board", "groups": ['Bolalar stomatologiyasi']},
    {"ru": "частичный протез", "uz": "qisman protez", "en": "partial denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "пациент", "uz": "bemor", "en": "patient", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "плательщик (страховщик)", "uz": "to'lovchi tomon", "en": "payer", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "детский стоматолог / детская стоматология", "uz": "bolalar stomatologi / bolalar stomatologiyasi", "en": "pediatric dentist / pediatric dentistry", "groups": ['Bolalar stomatologiyasi']},
    {"ru": "экспертная оценка (пир-ревью)", "uz": "hamkasblar tomonidan baholash", "en": "peer review", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "периапикальный", "uz": "periapikal", "en": "periapical", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "периапикальная рентгенограмма", "uz": "periapikal rentgenogramma", "en": "periapical radiograph", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "пародонтит / пародонтальная болезнь / пародонт", "uz": "parodontit / parodontal kasallik / parodont", "en": "periodontal disease / periodontitis / periodontium", "groups": ['Parodontologiya']},
    {"ru": "", "uz": "periodontal boylam", "en": "periodontal ligament", "groups": ['Ortodontiya']},
    {"ru": "пародонтальный карман", "uz": "parodontal cho'ntak", "en": "periodontal pocket", "groups": ['Parodontologiya']},
    {"ru": "пародонтология / пародонтолог", "uz": "parodontologiya / parodontolog", "en": "periodontics / periodontist", "groups": ['Parodontologiya']},
    {"ru": "периапикальный (околокорневой)", "uz": "ildiz atrofidagi (periradikulyar)", "en": "periradicular", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "", "uz": "doimiy tishlar qatori", "en": "permanent dentition", "groups": ['Ortodontiya']},
    {"ru": "штифт (пин)", "uz": "shtift (pin)", "en": "pin", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "зубной налёт (бляшка)", "uz": "tish g'ubori (nalyot, plak)", "en": "plaque", "groups": ['Parodontologiya']},
    {"ru": "тело мостовидного протеза (понтик)", "uz": "pontik (ko'prikning sun'iy tishi)", "en": "pontic", "groups": ['Ortopedik stomatologiya']},
    {"ru": "фарфор / керамика", "uz": "farfor / keramika", "en": "porcelain / ceramic", "groups": ['Ortopedik stomatologiya', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "штифтовая культевая вкладка (пост)", "uz": "post (ildiz kanaliga o'rnatiladigan tayanch)", "en": "post", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "задний (жевательный)", "uz": "orqa (chaynash) tishlar", "en": "posterior", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "силовая цепочка (пауэр-чейн)", "uz": "sheyn (kuch zanjiri)", "en": "power chain", "groups": ['Ortodontiya']},
    {"ru": "предварительное разрешение / подтверждение права / предопределение", "uz": "oldindan ruxsat / tasdiqlash / oldindan aniqlash", "en": "preauthorization / precertification / predetermination", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "премедикация", "uz": "premedikatsiya", "en": "premedication", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "страховая премия (взнос)", "uz": "sug'urta badali (premiya)", "en": "premium", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "", "uz": "kichik azob tish", "en": "premolar", "groups": ['Ortodontiya']},
    {"ru": "профилактическая стоматология", "uz": "profilaktik stomatologiya", "en": "preventive dentistry", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "sut tishlari qatori", "en": "primary dentition", "groups": ['Ortodontiya']},
    {"ru": "праймер", "uz": "praymer", "en": "primer", "groups": ['Ortodontiya']},
    {"ru": "прогнатия", "uz": "prognatiya", "en": "prognathism", "groups": ['Ortodontiya']},
    {"ru": "профилактическая чистка (профилактика)", "uz": "profilaktik tozalash (profilaktika)", "en": "prophylaxis", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "протез / протезирование / врач-протезист", "uz": "protez / protezlash (protetika) / protezist shifokor", "en": "prosthesis / prosthodontics / prosthodontist", "groups": ['Ortopedik stomatologiya']},
    {"ru": "стриппинг (сепарация, IPR)", "uz": "stripping (IPR)", "en": "proximal stripping (IPR — interproximal reduction)", "groups": ['Ortodontiya']},
    {"ru": "врач общественного стоматологического здоровья / стоматология общественного здоровья", "uz": "jamoat stomatologiyasi mutaxassisi / jamoat stomatologiyasi", "en": "public health dentist / public health dentistry", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "пульпа / полость пульпы / пульпит", "uz": "pulpa / pulpa bo'shlig'i / pulpit", "en": "pulp / pulp cavity / pulpitis", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "пульпэктомия / пульпотомия", "uz": "pulpektomiya / pulpotomiya", "en": "pulpectomy / pulpotomy", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "квадрант (четверть зубного ряда)", "uz": "kvadrant (tish qatorining to'rtdan bir qismi)", "en": "quadrant", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "радикулярный / периапикальный", "uz": "ildizga oid (radikulyar) / ildiz atrofidagi", "en": "radicular / periradicular", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "рентгенограмма (снимок)", "uz": "rentgenogramma (rentgen rasmi)", "en": "radiograph", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "рентгенохирургический имплантологический шаблон", "uz": "rentgen-jarrohlik implant shabloni", "en": "radiographic/surgical implant index", "groups": ['Implantologiya', 'Radiologiya / Diagnostika / Patologiya']},
    {"ru": "ребондинг (повторная фиксация брекета)", "uz": "re-bonding", "en": "re-bonding", "groups": ['Ortodontiya']},
    {"ru": "перебазировка протеза / релайнинг", "uz": "protez asosini almashtirish (rebaza) / relayning", "en": "rebase / reline", "groups": ['Ortopedik stomatologiya']},
    {"ru": "реминерализация (реккальцификация)", "uz": "qayta minerallashtirish (rekaltsifikatsiya)", "en": "recalcification", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "возмещение / перестрахование", "uz": "qoplama (kompensatsiya) / qayta sug'urtalash", "en": "reimbursement / reinsurance", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "реплантация зуба", "uz": "tishni qayta implantatsiya qilish (reimplantatsiya)", "en": "reimplantation, tooth", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "рецидив", "uz": "residiv", "en": "relapse", "groups": ['Ortodontiya']},
    {"ru": "съёмный частичный протез", "uz": "olinadigan qisman protez", "en": "removable partial denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "акриловая смола / инфильтрация смолой", "uz": "akril smola / smola bilan infiltratsiya", "en": "resin, acrylic / resin infiltration", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "резорбция (корня)", "uz": "rezorbsiya", "en": "resorption", "groups": ['Ortodontiya']},
    {"ru": "стоматология в торговых центрах", "uz": "savdo markazlaridagi stomatologiya", "en": "retail store dentistry", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "", "uz": "retayner (ushlab turuvchi)", "en": "retainer", "groups": ['Ortodontiya']},
    {"ru": "ретейнер (ортодонтический, протезный)", "uz": "reteyner (ortodontik, protez)", "en": "retainer (orthodontic, prosthodontic)", "groups": ['Ortodontiya', 'Ortopedik stomatologiya']},
    {"ru": "ретенционный период", "uz": "retensiya davri", "en": "retention period", "groups": ['Ortodontiya']},
    {"ru": "ретрогнатия", "uz": "retrognatiya", "en": "retrognathism", "groups": ['Ortodontiya']},
    {"ru": "ретроградное пломбирование", "uz": "retrograd plombalash", "en": "retrograde filling", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "корень / корневой канал / лечение корневых каналов / сглаживание поверхности корня", "uz": "ildiz / ildiz kanali / ildiz kanali davosi / ildizni silliqlash", "en": "root / root canal / root canal therapy / root planing", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "", "uz": "ildiz rezorbsiyasi", "en": "root resorption", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "rotatsiya (aylanish)", "en": "rotation", "groups": ['Ortodontiya']},
    {"ru": "", "uz": "elastik (rezinka)", "en": "rubber band", "groups": ['Ortodontiya']},
    {"ru": "коффердам (раббердам)", "uz": "kofferdam (raberdam)", "en": "rubber dam", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "слюнная железа", "uz": "so'lak bezi", "en": "salivary gland", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "скейлинг (снятие зубных отложений)", "uz": "skeyling (tish cho'kmalarini olib tashlash)", "en": "scaling", "groups": ['Parodontologiya']},
    {"ru": "герметик (силант)", "uz": "germetik (silant)", "en": "sealant", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Bolalar stomatologiyasi']},
    {"ru": "программа второго мнения", "uz": "ikkinchi fikr dasturi", "en": "second-opinion program", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "седативная (временная обезболивающая) пломба", "uz": "sedativ (og'riq qoldiruvchi) plomba", "en": "sedative filling", "groups": ['Terapevtik stomatologiya (Endodontiya)']},
    {"ru": "полупрецизионное крепление", "uz": "yarim-aniq mahkamlagich", "en": "semi-precision attachment", "groups": ['Ortopedik stomatologiya', 'Parodontologiya']},
    {"ru": "секстант", "uz": "sekstant", "en": "sextant", "groups": ['Terapevtik stomatologiya (Endodontiya)', 'Umumiy stomatologiya / Anatomiya']},
    {"ru": "сиалодохопластика / сиалография / сиалолитотомия", "uz": "sialodoxoplastika / sialografiya / sialolitotomiya", "en": "sialodochoplasty / sialography / sialolithotomy", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "паз брекета (слот)", "uz": "slot (breket o'yig'i)", "en": "slot (bracket slot)", "groups": ['Ortodontiya']},
    {"ru": "сохранитель места (спейс-мейнтейнер)", "uz": "joy saqlovchi apparat", "en": "space maintainer", "groups": ['Ortodontiya', 'Bolalar stomatologiyasi']},
    {"ru": "", "uz": "tishlar orasidagi bo'shliq", "en": "spacing", "groups": ['Ortodontiya']},
    {"ru": "шина (сплинт)", "uz": "shina (splint)", "en": "splint", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "стальная дуга", "uz": "poladdan tayyorlangan sim", "en": "stainless steel wire", "groups": ['Ortodontiya']},
    {"ru": "стоматит", "uz": "stomatit", "en": "stomatitis", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "постоянный зуб-преемник / сверхкомплектные зубы", "uz": "o'rin bosuvchi doimiy tish / ortiqcha (super komplekt) tishlar", "en": "succedaneous tooth / supernumerary teeth", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "супраокклюзия", "uz": "supraokklyuzion holat", "en": "supraocclusion", "groups": ['Ortodontiya']},
    {"ru": "шов (сутура)", "uz": "tikuv (sutura)", "en": "suture", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "таблица допустимых выплат", "uz": "ruxsat etilgan to'lovlar jadvali", "en": "table of allowances", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "временное опорное устройство (микроимплант, TAD)", "uz": "mikroimplant (TAD — vaqtinchalik tayanch qurilmasi)", "en": "temporary anchorage device (TAD) / mini-implant", "groups": ['Ortodontiya', 'Jarrohlik stomatologiyasi']},
    {"ru": "временный съёмный протез", "uz": "vaqtinchalik olinadigan protez", "en": "temporary removable denture", "groups": ['Ortopedik stomatologiya']},
    {"ru": "височно-нижнечелюстной сустав (ВНЧС) / дисфункция ВНЧС (ВНЧС-синдром)", "uz": "chakka-pastki jag' bo'g'imi (ChPJB) / ChPJB disfunksiyasi", "en": "temporomandibular (TMJ) / TMD", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "терапевтический", "uz": "terapevtik (davolovchi)", "en": "therapeutic", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "третья сторона / плательщик третьей стороны", "uz": "uchinchi tomon / uchinchi tomon to'lovchisi", "en": "third-party / third-party payer", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "наклон (типпинг)", "uz": "egilib harakatlanish (tipping)", "en": "tipping", "groups": ['Ortodontiya']},
    {"ru": "томография", "uz": "tomografiya", "en": "tomography", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "торк", "uz": "tork (aylanma bosim)", "en": "torque", "groups": ['Ortodontiya']},
    {"ru": "трахеотомия", "uz": "traxeotomiya", "en": "tracheotomy", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "трансплантация / трансплантация зуба", "uz": "transplantatsiya / tish transplantatsiyasi", "en": "transplantation / transplantation of tooth", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "транспозиция зубов", "uz": "transpozitsiya", "en": "transposition", "groups": ['Ortodontiya']},
    {"ru": "план лечения", "uz": "davolash rejasi", "en": "treatment plan", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "тризм (ограничение открывания рта)", "uz": "trizm (og'izni ocha olmaslik)", "en": "trismus", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "разделение процедур на составные части", "uz": "muolajalarni tarkibiy qismlarga ajratish", "en": "unbundling of procedures", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "", "uz": "teskari tishlanish (mezial)", "en": "underbite", "groups": ['Ortodontiya']},
    {"ru": "непрорезавшийся (о зубе)", "uz": "chiqmagan (tish haqida)", "en": "unerupted", "groups": ['Umumiy stomatologiya / Anatomiya']},
    {"ru": "использование услуг / управление использованием услуг", "uz": "xizmatlardan foydalanish / xizmatlardan foydalanishni boshqarish", "en": "utilization / utilization management", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "вертикальная прикусная рентгенограмма", "uz": "vertikal tishlanma rentgenogrammasi", "en": "vertical bitewing", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "вертикальный размер (окклюзионная высота)", "uz": "vertikal o'lcham (okklyuzion balandlik)", "en": "vertical dimension", "groups": ['Ortopedik stomatologiya']},
    {"ru": "вестибулопластика", "uz": "vestibuloplastika", "en": "vestibuloplasty", "groups": ['Jarrohlik stomatologiyasi']},
    {"ru": "вирусологический посев", "uz": "virusologik ekma (posev)", "en": "viral culture", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "период ожидания", "uz": "kutish davri", "en": "waiting period", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "восковая модель", "uz": "mumdan namuna (model)", "en": "wax pattern", "groups": ['Ortopedik stomatologiya']},
    {"ru": "компенсация работнику (за производственную травму)", "uz": "xodimga ish joyidagi jarohat uchun kompensatsiya", "en": "worker's compensation", "groups": ["Ma'muriy-sug'urta atamalari"]},
    {"ru": "ксеростомия (сухость во рту)", "uz": "kserostomiya (og'iz quruqligi)", "en": "xerostomia", "groups": ['Radiologiya / Diagnostika / Patologiya']},
    {"ru": "скуловая кость", "uz": "yonoq (zigomatik) suyagi", "en": "zygomatic bone", "groups": ['Umumiy stomatologiya / Anatomiya']},
]
